name: Trigger Elementor Pro Tests

on:
  push:
  pull_request:
    types: [labeled]

jobs:
  check-label:
    if: contains(github.event.pull_request.labels.*.name, 'run-pro-tests')
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Trigger Elementor-Pro Tests From Core
        run: |
          response=$(curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKE }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"event_type": "run-from-core", "client_payload": {"branch": "${{ steps.extract_branch.outputs.branch }}"}}' \
            https://api.github.com/repos/elementor/elementor-pro/dispatches)
