name: Trigger Remote Workflow and Wait

on:
  push:
  pull_request:

jobs:
  trigger_and_wait:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Trigger the remote workflow and wait for its completion
      - name: Trigger remote workflow and wait
        uses: anecdotes-ai/remote-workflow-control@latest
        with:
          github-auth-token: ${{  secrets.GITHUB_TOKEN }}
          workflow-org: 'baghdasarovelementor'
          workflow-repo: 'elementor-pro'
          workflow-yaml: 'playwright.yaml'
          workflow-branch: 'ED-15774-internal-execute-custom-core-tests-from-core-repo'
          workflow-inputs: '{\"types\": \"run-from-core\"}'
          wait-timeout-in-minutes: '20'

      # Step 2: Handle success/failure
      - name: Check conclusion
        if: success()
        run: echo "Remote workflow completed successfully!"

      - name: Handle failure
        if: failure()
        run: echo "Remote workflow failed!" && exit 1
