name: Trigger Remote Workflow and Wait

on:
  push:
  pull_request:

jobs:
  trigger_and_wait:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger remote workflow and wait
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: elementor
          repo: elementor-pro
          github_token: ${{ secrets.MAINTAIN_TOKEN }}
          github_user: elementorbot
          workflow_file_name: playwright.yml
          ref: main
          wait_interval: 10
          client_payload: '{"event_type": "run-from-core"}'
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true

      # Step 2: Handle success/failure
      - name: Check conclusion
        if: success()
        run: echo "Remote workflow completed successfully!"

      - name: Handle failure
        if: failure()
        run: echo "Remote workflow failed!" && exit 1
