name: Trigger Elementor Pro Tests

on:
  push:
  pull_request:
    types:
      -labeled

jobs:
  check-label:
    if: contains(github.event.pull_request.labels.*.name, 'run-pro-tests')
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Elementor-Pro Tests From Core
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/elementor/elementor-pro/actions/workflows/pro-tests-remote-workflow.yaml/dispatches \
            -d '{"ref":"main","inputs":{"trigger_uuid":"${{ github.sha }}"}}'
